# encoding: UTF-8

from objectmaphelper import *

thermostat_QQuickWindowQmlImpl = {"title": "Thermostat", "type": "QQuickWindowQmlImpl", "unnamed": 1, "visible": True}
thermostat_Thermostat_Control_Label = {"container": thermostat_QQuickWindowQmlImpl, "text": "Thermostat Control", "type": "Label", "unnamed": 1, "visible": True}
thermostat_ThermostatView = {"container": thermostat_QQuickWindowQmlImpl, "type": "ThermostatView", "unnamed": 1, "visible": True}
delegate_ThermostatScrollView = {"container": thermostat_ThermostatView, "id": "delegate", "type": "ThermostatScrollView", "unnamed": 1, "visible": True}
delegate_image_IconImage = {"container": delegate_ThermostatScrollView, "objectName": "image", "source": "qrc:/qt/qml/content/images/power.svg", "type": "IconImage", "visible": True}
delegate_handleItem_Rectangle = {"container": delegate_ThermostatScrollView, "id": "handleItem", "type": "Rectangle", "unnamed": 1, "visible": True}
thermostat_Rooms_Label = {"container": thermostat_QQuickWindowQmlImpl, "text": "Rooms", "type": "Label", "unnamed": 1, "visible": True}
delegate_image_IconImage_2 = {"container": delegate_ThermostatScrollView, "objectName": "image", "source": "qrc:/qt/qml/content/images/Cool", "type": "IconImage", "visible": True}
thermostat_Thermostat_Control_Label_2 = {"container": thermostat_QQuickWindowQmlImpl, "occurrence": 2, "text": "Thermostat Control", "type": "Label", "unnamed": 1, "visible": True}
o_CustomComboBox = {"container": thermostat_ThermostatView, "type": "CustomComboBox", "unnamed": 1, "visible": True}
thermostat_Overlay = {"container": thermostat_QQuickWindowQmlImpl, "type": "Overlay", "unnamed": 1, "visible": True}
comboBoxItem_ItemDelegate = {"checkable": False, "container": thermostat_Overlay, "id": "comboBoxItem", "occurrence": 2, "type": "ItemDelegate", "unnamed": 1, "visible": True}
thermostat_columnItem_ItemDelegate = {"checkable": False, "container": thermostat_QQuickWindowQmlImpl, "id": "columnItem", "occurrence": 2, "type": "ItemDelegate", "unnamed": 1, "visible": True}
delegate_Auto_CustomRoundButton = {"checkable": True, "container": delegate_ThermostatScrollView, "text": "Auto", "type": "CustomRoundButton", "unnamed": 1, "visible": True}
thermostat_toolBar_ToolBar = {"container": thermostat_QQuickWindowQmlImpl, "id": "toolBar", "type": "ToolBar", "unnamed": 1, "visible": True}
toolBar_Rectangle = {"color": "#ffffff", "container": thermostat_toolBar_ToolBar, "type": "Rectangle", "unnamed": 1, "visible": True}
thermostat_RoomsView = {"container": thermostat_QQuickWindowQmlImpl, "type": "RoomsView", "unnamed": 1, "visible": True}
scrollView_RoomsScrollView = {"container": thermostat_RoomsView, "id": "scrollView", "type": "RoomsScrollView", "unnamed": 1, "visible": True}
scrollView_toggle_CustomSwitch = {"checkable": True, "container": scrollView_RoomsScrollView, "id": "toggle", "type": "CustomSwitch", "unnamed": 1, "visible": True}
scrollView_circle_Rectangle = {"container": scrollView_RoomsScrollView, "id": "circle", "occurrence": 6, "type": "Rectangle", "unnamed": 1, "visible": True}
scrollView_background_Rectangle = {"container": scrollView_RoomsScrollView, "id": "background", "occurrence": 5, "type": "Rectangle", "unnamed": 1, "visible": True}
scrollView_Flickable = {"container": scrollView_RoomsScrollView, "type": "Flickable", "unnamed": 1, "visible": True}
comboBoxItem_ItemDelegate_2 = {"checkable": False, "container": thermostat_Overlay, "id": "comboBoxItem", "occurrence": 6, "type": "ItemDelegate", "unnamed": 1, "visible": True}
scrollView_image_IconImage = {"container": scrollView_RoomsScrollView, "objectName": "image", "source": "qrc:/qt/qml/content/images/Cool.svg", "type": "IconImage", "visible": True}
delegate_Cool_CustomRoundButton = {"checkable": True, "container": delegate_ThermostatScrollView, "text": "Cool", "type": "CustomRoundButton", "unnamed": 1, "visible": True}
scrollView_circle_Rectangle_2 = {"container": scrollView_RoomsScrollView, "id": "circle", "type": "Rectangle", "unnamed": 1, "visible": True}
delegate_Power_CustomRoundButton = {"checkable": True, "container": delegate_ThermostatScrollView, "id": "powerButton", "text": "Power", "type": "CustomRoundButton", "unnamed": 1, "visible": True}
delegate_Fan_CustomRoundButton = {"checkable": True, "container": delegate_ThermostatScrollView, "text": "Fan", "type": "CustomRoundButton", "unnamed": 1, "visible": True}
delegate_Heat_CustomRoundButton = {"checkable": True, "container": delegate_ThermostatScrollView, "text": "Heat", "type": "CustomRoundButton", "unnamed": 1, "visible": True}
delegate_Dry_CustomRoundButton = {"checkable": True, "container": delegate_ThermostatScrollView, "text": "Dry", "type": "CustomRoundButton", "unnamed": 1, "visible": True}
delegate_image_IconImage_3 = {"container": delegate_ThermostatScrollView, "objectName": "image", "source": "qrc:/qt/qml/content/images/Eco", "type": "IconImage", "visible": True}
scrollView_Cool_RoomOption = {"checkable": True, "container": scrollView_RoomsScrollView, "id": "roomOption", "text": "Cool", "type": "RoomOption", "unnamed": 1, "visible": True}
scrollView_toggle_CustomSwitch_2 = {"checkable": True, "container": scrollView_RoomsScrollView, "id": "toggle", "occurrence": 2, "type": "CustomSwitch", "unnamed": 1, "visible": True}
delegate_image_IconImage_4 = {"container": delegate_ThermostatScrollView, "objectName": "image", "source": "qrc:/qt/qml/content/images/Fan", "type": "IconImage", "visible": True}
delegate_image_IconImage_5 = {"container": delegate_ThermostatScrollView, "objectName": "image", "source": "qrc:/qt/qml/content/images/Dry", "type": "IconImage", "visible": True}
scrollView_Energy_Usage_12_KM_H_Label = {"container": scrollView_RoomsScrollView, "occurrence": 4, "text": "Energy Usage: 12 KM/H", "type": "Label", "unnamed": 1, "visible": True}
scrollView_Fan_RoomOption = {"checkable": True, "container": scrollView_RoomsScrollView, "id": "roomOption", "occurrence": 2, "text": "Fan", "type": "RoomOption", "unnamed": 1, "visible": True}
scrollView_toggle_CustomSwitch_3 = {"checkable": True, "container": scrollView_RoomsScrollView, "id": "toggle", "occurrence": 3, "type": "CustomSwitch", "unnamed": 1, "visible": True}
scrollView_Auto_RoomOption = {"checkable": True, "container": scrollView_RoomsScrollView, "id": "roomOption", "occurrence": 3, "text": "Auto", "type": "RoomOption", "unnamed": 1, "visible": True}
scrollView_toggle_CustomSwitch_4 = {"checkable": True, "container": scrollView_RoomsScrollView, "id": "toggle", "occurrence": 4, "type": "CustomSwitch", "unnamed": 1, "visible": True}
scrollView_Heat_RoomOption = {"checkable": True, "container": scrollView_RoomsScrollView, "id": "roomOption", "occurrence": 4, "text": "Heat", "type": "RoomOption", "unnamed": 1, "visible": True}
scrollView_background_Rectangle_2 = {"container": scrollView_RoomsScrollView, "id": "background", "occurrence": 8, "type": "Rectangle", "unnamed": 1, "visible": True}
scrollView_toggle_CustomSwitch_5 = {"checkable": True, "container": scrollView_RoomsScrollView, "id": "toggle", "occurrence": 5, "type": "CustomSwitch", "unnamed": 1, "visible": True}
scrollView_Dry_RoomOption = {"checkable": True, "container": scrollView_RoomsScrollView, "id": "roomOption", "occurrence": 5, "text": "Dry", "type": "RoomOption", "unnamed": 1, "visible": True}
scrollView_toggle_CustomSwitch_6 = {"checkable": True, "container": scrollView_RoomsScrollView, "id": "toggle", "occurrence": 6, "type": "CustomSwitch", "unnamed": 1, "visible": True}
scrollView_Eco_RoomOption = {"checkable": True, "container": scrollView_RoomsScrollView, "id": "roomOption", "occurrence": 6, "text": "Eco", "type": "RoomOption", "unnamed": 1, "visible": True}
scrollView_image_IconImage_2 = {"container": scrollView_RoomsScrollView, "objectName": "image", "source": "qrc:/qt/qml/content/images/Eco.svg", "type": "IconImage", "visible": True}
scrollView_circle_Rectangle_3 = {"container": scrollView_RoomsScrollView, "id": "circle", "occurrence": 3, "type": "Rectangle", "unnamed": 1, "visible": True}
scrollView_circle_Rectangle_4 = {"container": scrollView_RoomsScrollView, "id": "circle", "occurrence": 4, "type": "Rectangle", "unnamed": 1, "visible": True}
scrollView_circle_Rectangle_5 = {"container": scrollView_RoomsScrollView, "id": "circle", "occurrence": 5, "type": "Rectangle", "unnamed": 1, "visible": True}
thermostat_Stats_Label = {"container": thermostat_QQuickWindowQmlImpl, "text": "Stats", "type": "Label", "unnamed": 1, "visible": True}
thermostat_StatisticsView = {"container": thermostat_QQuickWindowQmlImpl, "type": "StatisticsView", "unnamed": 1, "visible": True}
o_StatisticsScrollView = {"container": thermostat_StatisticsView, "type": "StatisticsScrollView", "unnamed": 1, "visible": True}
chart_DeclarativeChart = {"container": o_StatisticsScrollView, "id": "chart", "type": "DeclarativeChart", "unnamed": 1, "visible": True}
scrollView_circle_Rectangle_6 = {"container": scrollView_RoomsScrollView, "id": "circle", "occurrence": 2, "type": "Rectangle", "unnamed": 1, "visible": True}
